### ISSUE TITLE
node版本可以升级吗

### ISSUE THREAD

**Issue by huoxiangdong** [louis-tru/quark#14]
nodejs的版本是8.9 ，可以升级到12，还是说很麻烦

**Comment by huoxiangdong** [comment]
好像npm模块是不能直接用的

**Comment by louis-tru** [comment]
nodejs升级确实比较麻烦，因为ios并不支持v8引擎，升级node必然要升级v8，v8-link这个工程需要修改。

npm应该是可以直接使用的，现在是报什么错误吗？

**Comment by huoxiangdong** [comment]
@louis-tru 
那expres测试了下
```
Error: Bad argument.
    at PackageIMPL.resolveRelative (_pkg.js:858:19)
    at resolveFilename (_pkg.js:540:30)
    at Function._load (_pkg.js:362:42)
    at Module.require (_pkg.js:275:23)
    at require (_pkgutil.js:238:20)
    at Object.<anonymous> (file:///Users/farmer/Library/Developer/CoreSimulator/Devices/0150AD7C-C740-4474-A6A7-49AEA6876B37/data/Containers/Bundle/Application/5BBF3B2E-CD9F-489B-91CD-FC72E381FCF8/test.app/examples/out/examples/index.js:6:17)
    at Module._compile (_pkg.js:306:42)
    at Object..js (_pkg.js:514:16)
    at Module.load (_pkg.js:269:38)
    at tryModuleLoad (_pkg.js:528:16)
threads count, 1
atexit_exec,name, 0x70000f9c2000, main
atexit_exec,join, 0x70000f9c2000
Thread::join(), cannot join self
```
![image](https://user-images.githubusercontent.com/18095882/99035095-d228d180-25b9-11eb-99a3-23c061c04b25.png)

**Comment by louis-tru** [comment]
可以在启动参数中加上--inspect-brk=0.0.0.0:9229看看具体的运行堆栈变量，

报这个错误应该是参数不正确。

**Comment by louis-tru** [comment]
可以试试最新的版本  v0.7.2 刚刚创建的新tag，ftrp已经同步到npm。

**Comment by huoxiangdong** [comment]
@louis-tru 希望大神有时间可以把TouchCode2更新下，兼容下最新的iPhone 🤪

**Comment by huoxiangdong** [comment]
@louis-tru 
引入express 报错，我试着引入其他库是OK的，是不是 _path的问题，express重写了_path? 覆盖掉了？

**Comment by louis-tru** [comment]
express属性于主出口项目，没有加入到node_modules中，但你可以使用node中的package.dependencies属性添加依赖

**Comment by louis-tru** [comment]
express在ivsg项目中是可以使用 import 'express' 引入的

**Comment by huoxiangdong** [comment]
@louis-tru 
然后，现在一直在这里循环
![image](https://user-images.githubusercontent.com/18095882/100090718-91209f00-2e8e-11eb-9fd8-7d0062b5ca7c.png)

**Comment by louis-tru** [comment]
> @louis-tru
> 然后，现在一直在这里循环
> ![image](https://user-images.githubusercontent.com/18095882/100090718-91209f00-2e8e-11eb-9fd8-7d0062b5ca7c.png)

你的具体项目是怎么样的，是在哪个项目引入这个`express`这个包的

**Comment by louis-tru** [comment]
![image](https://user-images.githubusercontent.com/1221969/100100270-86203b80-2e9b-11eb-8fb3-121a33c91f5b.png)

![image](https://user-images.githubusercontent.com/1221969/100100232-70ab1180-2e9b-11eb-91de-04e62587e9f0.png)
![image](https://user-images.githubusercontent.com/1221969/100100246-799be300-2e9b-11eb-96df-cfcd51913f8c.png)
![image](https://user-images.githubusercontent.com/1221969/100100255-7e609700-2e9b-11eb-82f3-bddce213ba0a.png)
这样引入是可以的

**Comment by louis-tru** [comment]
我不知道你的这个项目为什么安装后还有node_modules目录，正常安装后不应该有node_modules目录的，node_modules目录中的模块应该就被安装到根目录了

**Comment by louis-tru** [comment]
[test.zip](https://github.com/louis-tru/ftr/files/5590177/test.zip)
这个是项目文件
