### ISSUE TITLE
make xcode 报错

### ISSUE THREAD

**Issue by huoxiangdong** [louis-tru/quark#19]
```
Traceback (most recent call last):
  File "./libs/ftrp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "./libs/ftrp/gyp/pylib/gyp/__init__.py", line 552, in script_main
    return main(sys.argv[1:])
  File "./libs/ftrp/gyp/pylib/gyp/__init__.py", line 545, in main
    return gyp_main(args)
  File "./libs/ftrp/gyp/pylib/gyp/__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "./libs/ftrp/gyp/pylib/gyp/generator/xcode.py", line 1265, in GenerateOutput
    xct.FrameworksPhase().AddFile(library)
  File "./libs/ftrp/gyp/pylib/gyp/xcodeproj_file.py", line 1887, in AddFile
    self.AppendBuildFile(pbxbuildfile, path)
  File "./libs/ftrp/gyp/pylib/gyp/xcodeproj_file.py", line 1868, in AppendBuildFile
    self._AddBuildFileToDicts(pbxbuildfile, path)
  File "./libs/ftrp/gyp/pylib/gyp/xcodeproj_file.py", line 1858, in _AddBuildFileToDicts
    xcfilelikeelement.Name())
ValueError: Found multiple build files for -lz
make[1]: *** [xcode] Error 1
make: *** [xcode] Error 2
```
- make cmake-linux 也是
```
Traceback (most recent call last):
  File "./libs/ftrp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "./libs/ftrp/gyp/pylib/gyp/__init__.py", line 552, in script_main
    return main(sys.argv[1:])
  File "./libs/ftrp/gyp/pylib/gyp/__init__.py", line 545, in main
    return gyp_main(args)
  File "./libs/ftrp/gyp/pylib/gyp/__init__.py", line 530, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "./libs/ftrp/gyp/pylib/gyp/generator/cmake.py", line 1249, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
KeyError: 'outputs'
make[1]: *** [cmake-linux] Error 1
make: *** [cmake-linux] Error 2
```

**Comment by louis-tru** [comment]
你这是在哪个分支？

**Comment by huoxiangdong** [comment]
> 你这是在哪个分支？我在macos 10.15 / mastar 上运行没有发现在问题，xcode version 12.2
我在主分支master上也报错
macos 11.3 Version 12.4 (12D4e)

**Comment by louis-tru** [comment]
这个有可能与系统版本还有编译器有关，我还一直没有在11的系统上编译过，等过几天回北京了在我另外一台mac上试一下

**Comment by huoxiangdong** [comment]
> 这个有可能与系统版本还有编译器有关，我还一直没有在11的系统上编译过，等过几天回北京了在我另外一台mac上试一下

👌

**Comment by louis-tru** [comment]
你有没有构建成功，我在最新的系统上是可以通过的

**Comment by huoxiangdong** [comment]
> 你有没有构建成功，我在最新的系统上是可以通过的

我尝试用github action构建下试试，可能是我电脑环境的问题
到时如果还是有问题，我可以yml文件贴出来，这样你也可以方便查看问题在哪里

**Comment by huoxiangdong** [comment]
@louis-tru 
用action一直编译不过，报
error: libtool: can't open file: /Users/runner/work/Actions-macOS/Actions-macOS/ftr/out/ios.arm64.Release.shared/obj.target/v8-link/depe/v8-link/native-js.o (No such file or directory)

![image](https://user-images.githubusercontent.com/18095882/111559642-e11fca80-87cb-11eb-8838-e35ffb341ee9.png)

```yml
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
# 
# https://github.com/louis-tru/ftr.git
# Description: Build Ftr in macOS 10.15 using GitHub Actions
#


name: Build Ftr

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/louis-tru/ftr.git
  REPO_BRANCH: master
  
jobs:
   build:
    runs-on: macos-10.15

    steps:
    - name: Initialization environment
      run: |
        node -v
        npm i typescript@3.9.7 -g
        java -version
        brew search android-sdk
        brew install android-sdk
        export ANDROID_SDK="/usr/local/share/android-sdk"
        export ANDROID_NDK="/usr/local/share/android-ndk"
        echo $JAVA_HOME
        echo $ANDROID_SDK
        echo $ANDROID_NDK
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
    
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    - name: Clone source code
      #working-directory: /workdir
      run: git clone https://github.com/louis-tru/ftr.git
        
    - name: Init git submodule
      run: cd ftr && make init
      
    - name: Compile Ftr
      id: compile
      run: cd ftr && make install
